name: shutong
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - langchain-openai>=1.0.1
    - langgraph>=1.0.1
    - python-dotenv>=1.1.1
    - sympy>=1.12
    - numpy>=1.24.0
    - scipy>=1.11.0
    - streamlit>=1.28.0
